
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h2>THE ENERGY FITNESS SPECIALIST</h2>
        <h1>Quantum Fitness</h1>
        <nav>
          <Link href="/" passHref>
          <div>Home</div>
          </Link>
          <Link href="/events" passHref>
          <div>Servicios</div>
          </Link>
          <Link href="/about-us" passHref>
          <div >About me</div>
          </Link>
          {/* <a href="">Contacto</a> */}
        </nav>
      </header>
      <main className={styles.main}>
        {data.map((e) => (
          <Link key={e.id} href={`/events/${e.id}`} passHref>
          <div>
            <Image width={200} height={200} src={e.image} alt={e.title} />{" "}
            <h2>{e.title}</h2>
            <p>{e.description}</p>
          </div>
          </Link>
        ))}
      </main>
      <footer className={styles.footer}>
        <p>
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus
          quibusdam laudantium, quis rerum praesentium pariatur libero nesciunt
          eaque quod culpa sit, tempora corrupti repellendus animi deserunt
          consequuntur ipsam dolorem placeat?
        </p>
      </footer>
    </>
  );
}
export async function getServerSideProps() {
  const { events_categories } = await import("../data/data.json");
  return {
    props: {
      data: events_categories,
    },
  };
}
