import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h2>THE ENERGY FITNESS SPECIALIST</h2>
        <h1>Quantum Fitness</h1>
        <nav className="menu" id="menu">
          <a href="/">Home</a>
          <a href="/events">Servicios</a>
          <a href="/about-us">About me</a>
          {/* <a href="">Contacto</a> */}
        </nav>
      </header>
      <main className={styles.main}>
        <a href="" >
          <a href=""></a>
          <img src="" alt="" />
          <h2>Quantum Fitness</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae nobis delectus neque vitae blanditiis! Obcaecati, exercitationem modi. Laboriosam tenetur repellat quisquam temporibus fugiat. Dolore dolores a unde sint, doloremque ullam!</p>
        </a>
        <a href="" >
          <a href=""></a>
          <img src="" alt="" />
          <h2>Quantum Fitness evento 1</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae nobis delectus neque vitae blanditiis! Obcaecati, exercitationem modi. Laboriosam tenetur repellat quisquam temporibus fugiat. Dolore dolores a unde sint, doloremque ullam!</p>
        </a>
        <a href="" >
          <a href=""></a>
          <img src="" alt="" />
          <h2>Quantum Fitness evento 2</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae nobis delectus neque vitae blanditiis! Obcaecati, exercitationem modi. Laboriosam tenetur repellat quisquam temporibus fugiat. Dolore dolores a unde sint, doloremque ullam!</p>
        </a>
      </main>
      <footer className={styles.footer} >
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus quibusdam laudantium, quis rerum praesentium pariatur libero nesciunt eaque quod culpa sit, tempora corrupti repellendus animi deserunt consequuntur ipsam dolorem placeat?</p>
      </footer>
    </>
  );
}
