/* eslint-disable @next/next/no-html-link-for-pages */
/* eslint-disable @next/next/no-img-element */
/* eslint-disable react/jsx-key */
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
// import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h2>THE ENERGY FITNESS SPECIALIST</h2>
        <h1>Quantum Fitness</h1>
        <nav className="menu" id="menu">
          <a href="/">Home</a>
          <a href="/events">Servicios</a>
          <a href="/about-us">About me</a>
          {/* <a href="">Contacto</a> */}
        </nav>
      </header>
      <main className={styles.main}>
        {data.map((ev) => (
          <a key={ev.id} href={`/events/${ev.id}`}>
            {" "}
            <Image width={200} height={200} src={ev.image} alt={ev.title} /> <h2>{ev.title}</h2>
            <p>{ev.description}</p>
          </a>
        ))}
        
      </main>
      <footer className={styles.footer}>
        <p>
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus
          quibusdam laudantium, quis rerum praesentium pariatur libero nesciunt
          eaque quod culpa sit, tempora corrupti repellendus animi deserunt
          consequuntur ipsam dolorem placeat?
        </p>
      </footer>
    </>
  );
}
export async function getServerSideProps() {
  const { events_categories } = await import("../data/data.json");
  return {
    props: {
      data: events_categories,
    },
  };
}
